[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vualt = "3R6d7GRQFn1xiDKJDh3JyNMf5TEAPLgcCfc9C4xX6Rt8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/savvy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
