[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow = "CzSvoiPzRjUAANWHz824Hw4hPY5PqDHANJai6LDUYubW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/savvy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
